#!/usr/bin/env python3
"""Regenerate `kit/examples/example-report.md` by scanning the fixture it claims to describe.

    python3 scripts/gen_example_report.py
    python3 scripts/gen_example_report.py --check     # CI: fail if the committed file is stale

The example report is the artefact a reader opens to find out what this tool produces before
deciding whether to install it. It was written by hand, and by the time anybody checked it had
drifted almost completely away from the engine: it advertised **21 findings and one tool**, from
a scan taken before the taint tier, the structural analyses and the ReDoS analysis existed, and
it named a detector (`SEC-JS-PROTO`) that has since been retired. Every claim in it was
out of date and none of it was wrong on purpose — which is the whole argument for generating it.

Same rule as `docs/language-coverage.md`, `docs/what-we-miss.md`, `rules/secaudit/` and the
site's demo page: if it describes the engine, the engine writes it.
"""
from __future__ import annotations

import argparse
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KIT = os.path.join(REPO, "kit")
sys.path.insert(0, KIT)

from secaudit_core import engine, report                                      # noqa: E402

# Relative on purpose: it becomes the report's title, and an absolute path would put whichever
# machine last ran this into a committed file.
FIXTURE = os.path.join("tests", "fixtures", "vulnerable-app")
OUT = os.path.join(KIT, "examples", "example-report.md")

PREAMBLE = """\
<!-- Generated by scripts/gen_example_report.py — do not edit by hand.
     This is a real Tier-0 scan of tests/fixtures/vulnerable-app, the deliberately vulnerable
     fixture in this repository, rendered by the same code path `secaudit --format md` uses.
     Regenerate with: python3 scripts/gen_example_report.py -->

"""


def render() -> str:
    # The published configuration: no dependency tier, no external scanners, no model. Anything
    # else and the example would show output a reader cannot reproduce with one command.
    result = engine.scan(os.path.join(REPO, FIXTURE), run_deps=False, use_scanners=False)
    result.target = FIXTURE.replace(os.sep, "/")
    body = report.to_markdown(result)
    return PREAMBLE + body.rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError):
            pass
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed report is not what the engine produces")
    args = ap.parse_args(argv)

    fresh = render()
    if args.check:
        try:
            with open(OUT, encoding="utf-8") as fh:
                committed = fh.read()
        except OSError:
            committed = ""
        if committed.replace("\r\n", "\n") != fresh:
            print(f"FAIL — {os.path.relpath(OUT, REPO)} is not what a scan of {FIXTURE} "
                  f"produces. Run: python3 scripts/gen_example_report.py")
            return 1
        print(f"PASS  example report matches a live scan of {FIXTURE}")
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(fresh)
    lines = fresh.count("\n")
    print(f"Wrote {os.path.relpath(OUT, REPO)} — {lines} lines from a live scan of {FIXTURE}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
